### ISSUE TITLE
any news about the release date ??

### ISSUE THREAD

**Issue by MxMira** [Esri/data-collection-android#3]
Dear Mike,
I am working on a business case that would benefit a lot from your [data-collection-android] app.
So I need to know if there are any optimistic news about finishing soon.
@mikewilburn 
Thanks

**Comment by mikewilburn** [comment]
Hi Mohamed. We've tried to refrain from giving specific timelines as these things are generally in flux. At this time, we unfortunately do not have a specific release date to provide.

**Comment by MxMira** [comment]
Thanks Mike
